/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package convert;

import java.util.Random;
import javax.swing.Timer;
import java.awt.event.*;
import java.util.ArrayList;
import javafx.scene.control.Slider;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author User
 */
public class GUI extends JFrame {

    /**
     * Creates new form ConvertTemp
     */
    public GUI() {
        initComponents();

        tiempo = new Timer(1200, new ActionListener() {
//Inicjacja Timera odpowiadającego za Aanimację
            @Override
            public void actionPerformed(ActionEvent e) {

                if (i < 23) {
                    int b = 23 - i;
                    txtOut.setText("Oczekiwanie na wyciąg: " + b);
                    ICON.setIcon(new ImageIcon(getClass().getResource("/convert/icon" + i + ".png")));
                    i++;

                } else {
                    if (i == 23) {
                        PokazPrzyciski();
                        ICON.setIcon(new javax.swing.ImageIcon(getClass().getResource("/convert/icon0.png"))); // NOI18N 
                        txtOut.setText("Kolejka wróciła, teraz można zakupić bilet, czy chce Pan to zrobic?");
                        r = new Random();
                        i = r.nextInt(22);

                        Aktualizuj();
                    }
                    tiempo.stop();
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        bilety = new javax.swing.JPanel();
        butExit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtOut = new javax.swing.JTextArea();
        butTAK = new javax.swing.JButton();
        butNIE = new javax.swing.JButton();
        butPomoc = new javax.swing.JButton();
        TabbedPane = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        butCena = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        butGranica = new javax.swing.JToggleButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtCena = new javax.swing.JLabel();
        txtZmiana = new javax.swing.JLabel();
        txtGranica = new javax.swing.JLabel();
        txtInCena = new javax.swing.JTextField();
        txtInGranica = new javax.swing.JTextField();
        butZmien = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtPracownik = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtBaza = new javax.swing.JTextArea();
        kolejka = new javax.swing.JPanel();
        ICON = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("WYCIAG_NARCIARSKI");

        bilety.setBorder(javax.swing.BorderFactory.createTitledBorder("BILETY"));

        butExit.setText("Exit");
        butExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butExitActionPerformed(evt);
            }
        });

        txtOut.setColumns(20);
        txtOut.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        txtOut.setLineWrap(true);
        txtOut.setRows(5);
        txtOut.setText("Czy chcesz rozpocząć działanie programu : WYCIĄG NARCIARSKI ?");
        txtOut.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txtOut);

        butTAK.setText("TAK");
        butTAK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butTAKActionPerformed(evt);
            }
        });

        butNIE.setText("ANULUJ");
        butNIE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butNIEActionPerformed(evt);
            }
        });

        butPomoc.setText("POMOC :)");
        butPomoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butPomocActionPerformed(evt);
            }
        });

        TabbedPane.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 255)));
        TabbedPane.setVisible(false);

        butCena.setText("Zmień Cenę");
        butCena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butCenaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Zarządzaj ceną, obniżką, pracownikiem");

        jLabel3.setText("Do samoczynnej zmiany pozostało : ");

        butGranica.setText("Zmień Granicę Obniżki");
        butGranica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butGranicaActionPerformed(evt);
            }
        });

        jLabel4.setText("Obecna Cena: ");

        jLabel5.setText("Obecna Granica : ");

        txtInCena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInCenaActionPerformed(evt);
            }
        });

        butZmien.setText("Zmień Pracownika");
        butZmien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butZmienActionPerformed(evt);
            }
        });

        jLabel2.setText("Obecny Pracownik:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(butGranica)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtInGranica, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 32, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(butCena)
                        .addGap(64, 64, 64)
                        .addComponent(txtInCena, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtGranica))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCena))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtZmiana))
                    .addComponent(butZmien)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPracownik)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butCena)
                    .addComponent(txtInCena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtCena))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtZmiana))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butGranica)
                    .addComponent(txtInGranica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(txtGranica))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(butZmien)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPracownik))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TabbedPane.addTab("Zarządzaj", jPanel2);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Baza");

        txtBaza.setColumns(20);
        txtBaza.setLineWrap(true);
        txtBaza.setRows(5);
        txtBaza.setWrapStyleWord(true);
        jScrollPane2.setViewportView(txtBaza);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(jLabel9)
                .addContainerGap(126, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        TabbedPane.addTab("Baza", jPanel4);

        javax.swing.GroupLayout biletyLayout = new javax.swing.GroupLayout(bilety);
        bilety.setLayout(biletyLayout);
        biletyLayout.setHorizontalGroup(
            biletyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(biletyLayout.createSequentialGroup()
                .addGroup(biletyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, biletyLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(butExit))
                    .addGroup(biletyLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(butPomoc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(biletyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(biletyLayout.createSequentialGroup()
                                .addComponent(butTAK, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(316, 316, 316)
                                .addComponent(butNIE, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addComponent(TabbedPane)))
                .addContainerGap())
        );
        biletyLayout.setVerticalGroup(
            biletyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(biletyLayout.createSequentialGroup()
                .addGroup(biletyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(biletyLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(biletyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(butPomoc, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addGroup(biletyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(butTAK)
                            .addComponent(butNIE)))
                    .addComponent(TabbedPane))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(butExit)
                .addContainerGap())
        );

        kolejka.setBorder(javax.swing.BorderFactory.createTitledBorder("KOLEJKA"));
        kolejka.setToolTipText("Kolejka");

        ICON.setIcon(new javax.swing.ImageIcon(getClass().getResource("/convert/icon0.png"))); // NOI18N
        //jLabel1.setVisible(false);

        javax.swing.GroupLayout kolejkaLayout = new javax.swing.GroupLayout(kolejka);
        kolejka.setLayout(kolejkaLayout);
        kolejkaLayout.setHorizontalGroup(
            kolejkaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kolejkaLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(ICON)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        kolejkaLayout.setVerticalGroup(
            kolejkaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kolejkaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(ICON, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(kolejka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(bilety, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(kolejka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bilety, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(92, Short.MAX_VALUE))
        );

        bilety.getAccessibleContext().setAccessibleName("Bilety");
        kolejka.getAccessibleContext().setAccessibleName("Kolejka");
        kolejka.getAccessibleContext().setAccessibleDescription("");

        setSize(new java.awt.Dimension(1127, 756));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public Timer tiempo;
    Random r = new Random();
    int i = r.nextInt(22);
    int licznik_tak = 0;
    int licznik_bilet = 0;
    double cena = 15;
    static int granica = 10;
    Pracownik pracownik = new Pracownik();
    
    String log = "";

    public void ChowajPrzyciski() {
        butGranica.setVisible(false);
        butCena.setVisible(false);
        txtInCena.setVisible(false);
        txtInGranica.setVisible(false);
        butTAK.setVisible(false);
        butNIE.setVisible(false);
        butZmien.setVisible(false);
    }
    //Metoda Chgowaj ustawia przyciski które odpoiwadają za zarządzanie Wyciagiem na false, w zależności od momentu wykonywania programu

    public void PokazPrzyciski() {
        butGranica.setVisible(true);
        butCena.setVisible(true);
        txtInCena.setVisible(true);
        txtInGranica.setVisible(true);
        butTAK.setVisible(true);
        butNIE.setVisible(true);
        butZmien.setVisible(true);
    }
    //Metoda PokazPrzyciski ustawia przyciski które odpoiwadają za zarządzanie Wyciagiem na  true w zależności od momentu wykonywania programu

    public void Aktualizuj() {
        txtPracownik.setText(pracownik.getImie() + " " + pracownik.getNazwisko());
        txtZmiana.setText(licznik_str());
        txtCena.setText(cena_str());
        txtGranica.setText(granica_str());
    }
    //Metoda aktualizuj aktualizuje dane licznikowe, informacyjne widniejące w Tabeli

    public String licznik_str() {
        return Integer.toString(granica - licznik_bilet);

    }
    //Metoda ta zamienia wartosc obliczeniową licznika obniżkowego, na wartość STRING

    public String cena_str() {
        return String.format("%.2f", cena);
    }
    //Metoda ta zamienia wartosc obliczeniową ceny, na wartość STRING

    public String granica_str() {
        return Integer.toString(granica);
    }
        //Metoda ta zamienia wartosc obliczeniową granicy, na wartość STRING


    private void butExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_butExitActionPerformed

    private void butTAKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butTAKActionPerformed
        butPomoc.setVisible(false);
        Aktualizuj();

        if (licznik_tak == 0) {
            butTAK.setText("Dalej");
            TabbedPane.setVisible(true);
            PokazPrzyciski();
            txtOut.setText("Witam w Pogramie......Aby zakupić bilet wciśnij przycisk DALEJ");
        } else {
            if (licznik_tak == 1) {
                if (granica == licznik_bilet) {
                    cena = cena / 2;
                    granica = 10;
                }
                txtOut.setText("Należy poczekać na wyciąg!");
            } else if (licznik_tak == 2) {
                ChowajPrzyciski();
                txtOut.setText("Oczekiwanie........");
                tiempo.start();
            } else if (licznik_tak == 3) {
                licznik_bilet++;
                Random y = new Random();
                int g = r.nextInt(3);

                switch (g) {
                    case 0: {
                        Klient klient1 = new Klient(cena);
                        log = log + "Zakup: " + licznik_bilet + " " + "Kto: " + "Klient " + "Nazwisko: " + klient1.getNazwisko() + " " + "Imie: "
                                + klient1.getImie() + " " + "Przedział: " + klient1.getPrzedzial() + " " + "Województwo: " + klient1.getWojewodztwo() + " " + "Pracownik: " + pracownik.getImie() + " " + pracownik.getNazwisko() + " " + " " + "Cena biletu: " + klient1.getCena() + "////         ";
                    }
                    break;
                    case 1: {
                        Uczestnik klient1 = new Uczestnik(cena);
                        log = log + "Zakup: " + licznik_bilet + " " + "Kto: " + "Uczestnik " + "Nazwisko: " + klient1.getNazwisko() + " " + "Imie: "
                                + klient1.getImie() + " " + "Przedział: " + klient1.getPrzedzial() + " " + "Sprzęt: " + klient1.getSprzet() + " " + "Pracownik: " + pracownik.getImie() + " " + pracownik.getNazwisko() + " " + " " + "Cena biletu: " + klient1.getCena() + "////         ";
                    }
                    break;
                    case 2: {
                        Zwiedzajacy klient1 = new Zwiedzajacy(cena);
                        log = log + "Zakup: " + licznik_bilet + " " + "Kto: " + "Zwiedzajacy " + "Nazwisko: " + klient1.getNazwisko() + " " + "Imie: "
                                + klient1.getImie() + " " + "Przedział: " + klient1.getPrzedzial() + " " + "Miejsce: " + klient1.getMiejsce() + " " + "Pracownik: " + pracownik.getImie() + " " + pracownik.getNazwisko() + " "
                                + " " + "Cena biletu: " + klient1.getCena() + "////         ";
                    }
                    break;

                }
                txtBaza.setText(log);
                txtOut.setText("Bilet Został zakupiony : informacje w części - Baza -> Log -              Aby zakupić kolejny proszę wcisnąć przycisk - Powtórz -");
                butTAK.setText("Powtórz");
                licznik_tak = -1;

            } else {

            }
        }
        licznik_tak++;
    }//GEN-LAST:event_butTAKActionPerformed

    private void butPomocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butPomocActionPerformed
        txtOut.setText("Przycisk - TAK rozpoczyna program.                Aby Przerwać Działanie programu należy wcisnąć przycisk EXIT"
                + "        Program daje możliwość zakupieni biletu wynegrenowanego autoamtycznie bądz za pośrednictwem  systemu Menadżeringu");        // TODO add your handling code here:


    }//GEN-LAST:event_butPomocActionPerformed

    private void butNIEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butNIEActionPerformed
        txtOut.setText("Anulowano Program, aby kupić wcziśnik KUP");
        licznik_tak = 0;
        butTAK.setText("Kup");
        butNIE.setVisible(false);
        TabbedPane.setVisible(false);
//Odpowiednie kroki aby powrócić do stanu początkowego licznika_TAK

    }//GEN-LAST:event_butNIEActionPerformed

    private void txtInCenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInCenaActionPerformed

    }//GEN-LAST:event_txtInCenaActionPerformed

    private void butGranicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butGranicaActionPerformed

        try {
            granica = Integer.parseInt(txtInGranica.getText());
            if (granica < 0) {
                granica = (granica * (-1));
            }
            if (granica == 0) {
                granica = 1;
            }
            Aktualizuj();
            butGranica.setSelected(false);
            txtInGranica.setText("");
            licznik_bilet = 0;
        } catch (NumberFormatException e) {
            txtOut.setText("Musi być liczba!");
            licznik_tak = 0;
            butNIE.setVisible(false);
            butTAK.setText("OK");
            butGranica.setSelected(false);
        }
//Przycisk umożliwający zmianę granicy
        // TODO add your handling code here:
    }//GEN-LAST:event_butGranicaActionPerformed

    private void butCenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butCenaActionPerformed

        try {
            cena = Double.parseDouble(txtInCena.getText());
            if (cena < 0) {
                cena = (cena * (-1));
            }
            Aktualizuj();
            butCena.setSelected(false);
            txtInCena.setText("");

        } catch (NumberFormatException e) {
            txtOut.setText("Musi być liczba!");
            licznik_tak = 0;
            butNIE.setVisible(false);
            butTAK.setText("OK");
            butCena.setSelected(false);
        }
        //Przycisk umozliwający zmianę Ceny Biletu
    }//GEN-LAST:event_butCenaActionPerformed

    private void butZmienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butZmienActionPerformed
        pracownik.zmien_pracownika();
        Aktualizuj();
        // TODO add your handling code here:
    }//GEN-LAST:event_butZmienActionPerformed

    /**
     * @param args the command line arguments
     */
    public final static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new GUI().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ICON;
    private javax.swing.JTabbedPane TabbedPane;
    private javax.swing.JPanel bilety;
    private javax.swing.JToggleButton butCena;
    private javax.swing.JButton butExit;
    private javax.swing.JToggleButton butGranica;
    private javax.swing.JButton butNIE;
    private javax.swing.JButton butPomoc;
    private javax.swing.JButton butTAK;
    private javax.swing.JButton butZmien;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel kolejka;
    private javax.swing.JTextArea txtBaza;
    private javax.swing.JLabel txtCena;
    private javax.swing.JLabel txtGranica;
    private javax.swing.JTextField txtInCena;
    private javax.swing.JTextField txtInGranica;
    private javax.swing.JTextArea txtOut;
    private javax.swing.JLabel txtPracownik;
    private javax.swing.JLabel txtZmiana;
    // End of variables declaration//GEN-END:variables

}
